### ISSUE TITLE
Priority Dropdown Text Display – Dark Mode

### ISSUE THREAD

**Issue by DonaldSchepis** [auctumnus/gvc#2]
![GVC_PriorityDropdown](https://github.com/user-attachments/assets/d5428fd7-31f3-4d2b-8e35-ce9a09417d78)

When signing up for an event, the numerals in the **Priority** dropdown are not visible unless you hover over the items in the list when using dark mode.

The issue persists when editing priority in an event sign-up as well.

**Comment by auctumnus** [comment]
just pushed something that should fix this - can you check on how it looks now? if it's still not visible, what operating system and browser are you using?

**Comment by DonaldSchepis** [comment]
![image](https://github.com/user-attachments/assets/f22c9284-e105-480b-b6db-0b83ac8602bf)

Looks sorted!
